services:
  app:
    build: .
    image: node-ona
    environment:
      MONGO_URI: mongodb://172.22.0.2:27017/DB_User_management_service  # MongoDB connection string
      JWT_SECRET: dd4f18b44939205a7318a150684da1237f640ea67251b8d92e0a87f0817c5820
      PORT: 5000  # Port the app runs on
    ports:
      - '5000:5000'  # Map port 5000 on the host to port 5000 on the container
    depends_on:
      - mongo_ONA  # Ensure that the app waits for mongo to start
    volumes:
      - .:/src
    networks:
      - network_App_Mongo_ONA  # Attach to the custom network

  mongo_ONA:
    image: mongo:6-jammy  # Use the latest MongoDB image
    ports:
      - '27017:27017'  # Map MongoDB port
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data
    networks:
      - network_App_Mongo_ONA  # Attach to the custom network

volumes:
  mongo_data: # Define a volume to persist MongoDB data

networks:
  network_App_Mongo_ONA:  # Define the custom network
     driver: bridge
